### ISSUE TITLE
Cards not displayed in Google Assistant Simulator

### ISSUE THREAD

**Issue by gpalozzi** [dialogflow/dialogflow-fulfillment-nodejs#12]
Hi,

My webhook is returning the response below:

```
{
  "conversationToken": "[\"employee\"]",
  "expectUserResponse": true,
  "expectedInputs": [
    {
      "inputPrompt": {
        "richInitialPrompt": {
          "items": [
            {
              "simpleResponse": {
                "textToSpeech": "Welcome to Smart Pension.  You can ask a question like, what's my summary...",
                "displayText": "Welcome to Smart Pension.  You can ask a question like, what's my summary..."
              }
            },
            {
              "basicCard": {
                "title": "Title: this is a card title",
                "formattedText": "This is the body text of a card.  You can even use line\n  breaks and emoji! 💁",
                "image": {
                  "url": "https://s3-eu-west-1.amazonaws.com/mediasp/google-home/images/google-app-blue-1280-720.png",
                  "accessibilityText": "accessibility text"
                },
                "buttons": [
                  {
                    "title": "This is a button",
                    "openUrlAction": {
                      "url": "https://my.autoenrolment.co.uk"
                    }
                  }
                ]
              }
            },
            {
              "simpleResponse": {
                "textToSpeech": "Now, what can I help you with?",
                "displayText": "Now, what can I help you with?"
              }
            }
          ],
          "suggestions": [
            {
              "title": "My personal information"
            },
            {
              "title": "My summary"
            }
          ]
        }
      },
      "possibleIntents": [
        {
          "intent": "assistant.intent.action.TEXT"
        }
      ]
    }
  ],
  "responseMetadata": {
    "status": {},
    "queryMatchInfo": {
      "queryMatched": true,
      "intent": "2b8d59af-3daf-4f02-8b3e-848f67b7accc"
    }
  }
}
```
but I cannot see the card since I upgraded to the beta version.

<img width="398" alt="screen shot 2018-03-16 at 19 44 13" src="https://user-images.githubusercontent.com/9222374/37541467-a1526dfc-2952-11e8-857b-091fad842201.png">

this is the code I'm using to create the response:

```
          agent.add(`Welcome to Smart Pension.  You can ask a question like, what's my summary...`);

          agent.add(new Card({
              title: `Title: this is a card title`,
              imageUrl: smartPensionLogo,
              text: `This is the body text of a card.  You can even use line\n  breaks and emoji! 💁`,
              buttonText: 'This is a button',
              buttonUrl: smartPensionMyUrl
            })
          );
          agent.add(`Now, what can I help you with?`);
          agent.add(new Suggestion(`My personal information`));
          agent.add(new Suggestion(`My summary`));
```

Could you help me to solve this issue?

**Comment by matthewayne** [comment]
Do you see any errors of debug information in the Actions on Google simulator?

**Comment by positlabs** [comment]
You might have too many items in richInitialPrompt. I think I remember reading that the limit is two response items per user input.

**Comment by matthewayne** [comment]
Looks like a Actions on Google simulator issue, investigating...

Potential workaround is to use your phone (Just say "talk to my test app", or "talk to <INVOCATION_NAME>" on your phone when logged into the same Google account).

**Comment by matthewayne** [comment]
This should be fixed now, it was an issue on the Actions on Google simulator

**Comment by r2roesk** [comment]
@matthewayne still not fixed on my end. Code works on the side simulator, but I'm using the web integration and just get one text message.

**Comment by sravyagajavalli** [comment]
Hi,
Is it possible to choose a particular  card and store the details of the card i.e If I click on one card out of 10 cards I should store the data of that card(i.e name, imageUrl) in one variable
