### ISSUE TITLE
Multiple messages not supported with payloads

### ISSUE THREAD

**Issue by vmkrish** [dialogflow/dialogflow-fulfillment-nodejs#35]
When using a payload with the V2 agent, only the payload gets sent on platforms that support multiple message responses (eg, Facebook).

Eg,:

```
    agent.add(new Text({'text': 'hello', 'platform': 'FACEBOOK'}))
    agent.add(new Payload('FACEBOOK', {...})
```

will only send the payload, as opposed to both 'hello' and the payload

**Comment by McGern** [comment]
Came across this issue today. Would be great to have a update for this.

**Comment by Ashwin-Kapes** [comment]
If multiple messages are supported using Dialogflow UI, then why not using library. Is there any alternate way or trick to do so?

**Comment by stevenbeck** [comment]
This should be fixed by #113

**Comment by secato** [comment]
Same issue here, so #113 was merged but not deployed yet?

**Comment by jdpowell1** [comment]
@stevenbeck unfortunately #113 didn't fix this (at least for Facebook Messenger) Please check #147

**Comment by puuga** [comment]
#113 Still didn't fix this on Facebook Messenger.
If there is Payload in response along with others, will display only Payload.

**Comment by parnus01** [comment]
confirm about this issue . if mix message and payload it will response only payload type

**Comment by Ashwin-Kapes** [comment]
I've updated package to `dialogflow-fulfillment@^0.6.1`

Event after adding `{sendAsMessage: true}` , only payload is shown.

Is there anything else to modify?

**Comment by maganap** [comment]
@Ashwin-Kapes `dialogflow-fulfillment@^0.6.1` does not include fixes from #173.  Although it's already merged, you'll need to wait until package is bumped to 0.6.2 and published to be available on `npm`.

In the meantime, just clone from the latest commit here, and you can send text + payload like:

```js
agent.add( new Text('Hello there') );
agent.add( new Payload(agent.FACEBOOK, payload, {sendAsMessage:true}) );
```

I tested with current latest commit (`aaade16`) and it does work, `Text` + `Payload`.

**Comment by derit** [comment]
> @Ashwin-Kapes `dialogflow-fulfillment@^0.6.1` does not include fixes from #173. Although it's already merged, you'll need to wait until package is bumped to 0.6.2 and published to be available on `npm`.
> 
> In the meantime, just clone from the latest commit here, and you can send text + payload like:
> 
> ```js
> agent.add( new Text('Hello there') );   // or just agent.add('hello');
> agent.add( new Payload(agent.FACEBOOK, payload, {sendAsMessage:true}) );
> ```
> 
> I tested with current latest commit (`aaade16`) and it does work, `Text` + `Payload`.

i tested latest commit (c36cf9c), same in telegram, multiple payload not work
error result Payload response for TELEGRAM already defined.

**Comment by GuineaPigHealthTechnologies** [comment]
Any updates to this issue? I am still unable to send two custom payloads, e.g.

agent.add(new Payload(agent.FACEBOOK, payload1, {sendAsMessage: true}));
agent.add(new Payload(agent.FACEBOOK, payload2, {sendAsMessage: true}));

**Comment by tyylynette** [comment]
I'm still unable to send two custom payloads for Telegram, are there any fixes for this? Thanks 
```
agent.add(new Payload(agent.TELEGRAM, payload1, {sendAsMessage: true}));
agent.add(new Payload(agent.TELEGRAM, payload2, {sendAsMessage: true}));
```

**Comment by j4iro** [comment]
are there any fixes for this? Thanks

**Comment by jawwadturabi** [comment]
any update on this issue?

**Comment by nguyendn** [comment]
any update on this issue?

**Comment by anasvp444** [comment]
any updates?

**Comment by chunkhai96** [comment]
Lol, already 3 years to wait for this feature

**Comment by chunkhai96** [comment]
Lol, it's been 3 years to wait for this feature
