### ISSUE TITLE
Issues with the Actions on Google Sample. Throwing an error for response received by Actions on Google Simulator

### ISSUE THREAD

**Issue by SiddAjmera** [dialogflow/dialogflow-fulfillment-nodejs#59]
So I tried the sample, but I'm getting an error at other Intent Handler for Actions on Google. The error that I'm getting on the Actions on Google Simulator reads:

> MalformedResponse
expected_inputs[0].input_prompt.rich_initial_prompt: 'item[1]' must not be empty.

**Here's a screenshot for the same**

![image](https://user-images.githubusercontent.com/5053266/40282160-9dd545d2-5c88-11e8-8f58-687b6bb60c00.png)

**Comment by matthewayne** [comment]
What sample are you using?

**Comment by SiddAjmera** [comment]
@matthewayne , I'm using [this sample.](https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/samples/actions-on-google/functions/index.js)

**Comment by matthewayne** [comment]
This was fixed in v0.4.1

**Comment by sburrell63** [comment]
I'm using v0.4.1 and still seeing the issue identified on this thread.  ???
